### ISSUE TITLE
`doom_regression` GitHub Action random fails

### ISSUE THREAD

**Issue by ArtemkaKun** [vlang/c2v#41]
Randomly throws the following error

```
2s
Run ./imgur.sh /tmp/fail.png
Delete page: https://imgur.com/delete/r54LbMGifWieLxc
https://i.imgur.com/6wA7qov.png
Haven't copied to the clipboard: no xsel or xclip
https://i.imgur.com/PmdV4LZ.png
Delete page: https://imgur.com/delete/Ypna8rul9At2rno
Haven't copied to the clipboard: no xsel or xclip
Error: Process completed with exit code 1.
```

@Larpon

**Comment by Larpon** [comment]
If you are 100% sure that Doom starts and there is no runtime problems, then:
Yes, there's small chances that this can happen when CI is slow / pressured. There's no immediate reliable fix to the problem since the heuristics are all time based. I'll try to think of something to make the heuristics more reliable when the machine running it is under pressure.

We have a ~5 second window where the title screen is showed. So if the game is more than 7 seconds to start up and render the first frame the CI will fail.

I have had it on my TODO to add region based checks for render output - that would probably lower the chances a great bit for it to give false positives.

**Comment by ArtemkaKun** [comment]
Thank for clarification :)

**Comment by Larpon** [comment]
@ArtemkaKun let me know if the problem persists.
Should be improved greatly with: https://github.com/vlang/v/pull/15651
